env:
  global:
    - CC_TEST_REPORTER_ID=cefed7dd48416c591984e8c890a5a793137a1d9c5a83ea8155c15d566c6908c2

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

language: php
php:
  - '7.0.8'

install:
  - composer self-update
  - make install

script: make lint test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT