language: php
php:
  - '7.0.8'

install:
  - composer self-update
  - make install

addons:
  code_climate:
    repo_token:
      secure:"VwEhhev5dYib6C+RC9zr9uCbUnX6HTcZqFNOibPqsmTY5d2j5b9vNYrxfErFqJ8Tc80u26S0/C05zW+rfT0gN4Du+EnfdjiMbh/NnanfBHZk0FBupH9fzJ/UcXlV0ajdrGelf464N173dSa1SqGS9rPe6TizbOhpCohEaHrNaU7pn/m2zdSqMyWwipstn6chtR9POjl/Ge3LGY6TWbs1VF9GBAgDNol8GqLPrrsSGCX1+/Fr2I2IgRlrVlR1LGjeaIbrhvmAzNLBWJuiPwUkR5QlAvdShovHeEkrgnI3qCSydUVRW4kuvNkdYJqCnUdAcHvOQHqgWNrZs1c5W6JrLkCxiQ0sYsDRjxU1d55bCJTp/0nyj8mNktHkjh4CxJYx7ffl1Qn58O+YrKeDMqGh+h/w+EBkYWfGF2PZQRG3Pu0IQas5hHIYqgSu63qLGSVJIiKCeeVx0d8ValdA9o9AJ7QMUYDY7imErGY/YB89ogjLUvz7e+HX9m8YAhzSCfuZ+GQxUeXtSUkmt7IU3BMWP54po5T6nHwvj8mf37nalEgQbzXLh9kFNuiy32YQzHM3EUtnIDgM6v8qwV27+lhSq+JFNiqYuiNF1mefBDj8KVNipEM+AOz0SmQZIClxUmhTnld+kyO2but9vQfMtNnFmiWNRwHL6NEkKMB+JW9k+vo="

script: make lint test

after_script:
  - vendor/bin/test-reporter