language: php
php:
  - '7.0.8'

install:
  - composer self-update
  - make install

addons:
  code_climate:
    repo_token:
      secure:"tRRcPGH4DLpjNJlxWCfOmrSAJEjqK6L1lDKAVP8s57oAnVaYwUxS/nbV/HUkHU5rd6zRrCd20ybU4WwwbSty4vHIc24T6Rahh7qn3AGhzDwI4YxARhNU23EK30vtqnw1Wd4y3nRKkI21Kg4+TBL7l0lmqVVggAAdpiRmIerX1S4WHnTvjfvkMUD+c/xuMX8W7FLP6K0XcsgDjyKD+fWzZW5LOKl/Izwlstn0t8nUvWXq9L+Yp3Zfd+tuxoHiAWbYxFnj2EnOOwkIQ1nmaPobsEr9KBxY0qCL2seN+lFMH+flbUPabYjn3jaHElWJ1Rt+XkHTOgmp7qX6l65gabkyFG5qlXUs23S0xyBQbVpQHu3Zp1SW2KmjPa8XOSe4uQ8TwHMMy+cL6fOlj6yhaunokqPoog6alVxQa390M5IITtfs0NPNwwnr2wITi3mS/zwtB7FihV29rSuMVWEdtCe/UGIPEDs//LGududRGD9ROCCVAZrzru0Lv0ceSQSXZWHCMNpg3lQ4Dms9wrv1g6Y0ZM0Bm3buZCrdcalNJAzMA2XlKJARZJ/p3OGvQuuLSLBU6f2jULSZwvb4nNQPvCkfwEx+oiRwEukWJN5YPcu6ZS++hCdGdR0G+6e+Nci2Csyr6zbnMfamWWBb3KhkZjWBl5dVNEWe9+uqVFpqtWpdxUI="

script: make lint test

after_script:
  - vendor/bin/test-reporter